name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  Cancel-previous-jobs:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: khan/pull-request-workflow-cancel@1.0.0
        with:
          workflows: "main.yml"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

#  Formatting:
 #   runs-on: ubuntu-latest
  #  steps:
   #   - uses: actions/checkout@v2
    #  - name: Formatting
     #   uses: github/super-linter@v4.10.1
      #  env:
       #   VALIDATE_ALL_CODEBASE: false
        #  DEFAULT_BRANCH: master
         # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #FILTER_REGEX_EXCLUDE: CHANGELOG.md
          #VALIDATE_SNAKEMAKE_SNAKEFMT: true
          #VALIDATE_PYTHON_BLACK: true
          #VALIDATE_MARKDOWN: true

#  Linting:
 #   runs-on: ubuntu-latest
  #  steps:
   #   - uses: actions/checkout@v2
    #  - name: Lint workflow
     #   uses: snakemake/snakemake-github-action@v1
      #  with:
       #   directory: .
        #  snakefile: workflow/Snakefile
         # args: "--lint"
